import {GameEngine} from './game.js';
import {CHAMPIONS,COMPONENTS,ITEMS,AUGMENTS,OBJECTIVES} from './data.js';

const app=document.querySelector('#app');
const SAVE_KEY='bgtf-save-v1';
let game=null, activePlayerId=null, selectedMarket=new Set(), selectedCard=null, audioEnabled=true, reduceMotion=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const champ=id=>CHAMPIONS.find(x=>x.id===id);
const item=id=>ITEMS.find(x=>x.id===id);
const component=id=>COMPONENTS.find(x=>x.id===id);
const aug=id=>Object.values(AUGMENTS).flat().find(x=>x.id===id);
const objective=id=>OBJECTIVES.find(x=>x.id===id);

function save(){if(game)localStorage.setItem(SAVE_KEY,game.serialize());}
function load(){const raw=localStorage.getItem(SAVE_KEY);if(!raw)return false;try{game=GameEngine.fromSave(raw);activePlayerId=game.state.nguoiChoi[0].id;return true;}catch(e){localStorage.removeItem(SAVE_KEY);return false;}}
function beep(kind='tap'){if(!audioEnabled)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=kind==='star'?720:kind==='hurt'?170:kind==='level'?520:300;g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.16);o.start();o.stop(c.currentTime+.17);}catch{}}
function act(fn,kind='tap'){try{fn();save();beep(kind);render();}catch(e){toast(e.message,'loi');}}
function toast(msg,type='ok'){let el=document.querySelector('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.append(el);}el.textContent=msg;el.dataset.type=type;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2200);}

function newGameScreen(){
  const rows=Array.from({length:8},(_,i)=>`<label class="name-row"><span>${i+1}</span><input id="p${i}" value="${i<2?`Người chơi ${i+1}`:''}" placeholder="Tên người chơi ${i+1}" /></label>`).join('');
  app.innerHTML=`<main class="landing">
    <section class="hero"><div class="eyebrow">TRÒ CHƠI CHIẾN THUẬT • 2–8 NGƯỜI</div><h1>TFT: <strong>Hội Tụ Chiến Thuật</strong></h1><p>Quản lý kinh tế, đọc Chợ Chung, tranh tướng, nâng Cấp, ghép Sao, xây Tộc/Hệ và tích lũy Điểm Danh Vọng qua 12 Vòng Đấu.</p></section>
    <section class="setup parchment"><div class="setup-head"><h2>Tạo ván mới</h2><label>Số người chơi <select id="count">${[2,3,4,5,6,7,8].map(n=>`<option>${n}</option>`).join('')}</select></label></div><div id="names" class="names">${rows}</div><div class="setup-actions"><button class="primary" id="start">Bắt đầu ván</button>${localStorage.getItem(SAVE_KEY)?'<button id="continue">Tiếp tục ván đã lưu</button>':''}<button id="rules-home">Luật nhanh</button></div><p class="source-note">Bộ máy luật bám Rulebook v4.0. Gói nội dung tướng/Lõi/Kỳ Ngộ hiện là dữ liệu khởi tạo để web có thể chơi; có thể thay bằng bộ thẻ chính thức mà không đổi bộ máy luật.</p></section>
  </main>`;
  const count=document.querySelector('#count');function updateNames(){document.querySelectorAll('.name-row').forEach((r,i)=>r.hidden=i>=+count.value);}count.onchange=updateNames;updateNames();
  document.querySelector('#start').onclick=()=>{const n=+count.value,names=Array.from({length:n},(_,i)=>document.querySelector(`#p${i}`).value.trim()||`Người chơi ${i+1}`);game=new GameEngine(names,`BGTF-${Date.now()}`);activePlayerId=game.state.nguoiChoi[0].id;save();render();};
  document.querySelector('#continue')?.addEventListener('click',()=>{if(load())render();});
  document.querySelector('#rules-home').onclick=()=>showRules();
}

function render(){if(!game)return newGameScreen();const s=game.state,p=game.player(activePlayerId)||s.nguoiChoi[0];activePlayerId=p.id;document.body.classList.toggle('reduce-motion',reduceMotion);
  app.innerHTML=`<div class="game-shell">
    ${topbar(s,p)}
    <div class="table-layout">
      <aside class="players-rail">${s.nguoiChoi.map(playerChip).join('')}</aside>
      <main class="board-area">
        ${specialPanel(s)}
        ${marketPanel(s)}
        ${playerBoard(p)}
      </main>
      <aside class="right-rail">${roundTrack(s)}${traitsPanel(p)}${logPanel(s)}</aside>
    </div>
    ${actionDock(s,p)}
  </div>`;
  wire();
}

function topbar(s,p){return `<header class="topbar"><div><div class="brand-mini">TFT</div><b>HỘI TỤ CHIẾN THUẬT</b></div><div class="round-title"><span>Giai Đoạn ${roman(s.giaiDoan)}</span><strong>Vòng ${s.vong}/12</strong><small>${phaseName(s)}</small></div><div class="top-actions"><button data-cmd="save">Lưu ván</button><button data-cmd="rules">Luật</button><button data-cmd="settings">Âm ${audioEnabled?'bật':'tắt'}</button><button data-cmd="home">Thoát</button></div></header>`;}
function playerChip(p){const active=p.id===activePlayerId;return `<button class="player-chip ${active?'active':''}" data-player="${p.id}"><span class="avatar">${esc(p.ten).slice(0,1).toUpperCase()}</span><span class="pcopy"><b>${esc(p.ten)}</b><small>♥ ${p.mau} · ◈ ${p.vang} · Cấp ${p.cap}</small></span><span class="fame">${p.diemDanhVong}</span></button>`;}
function phaseName(s){return {'ky-ngo':'Vòng Kỳ Ngộ','loi':'Lõi Nâng Cấp','chuan-bi':`Nhịp Chuẩn Bị ${s.nhipChuanBi}/4`,'sap-doi-hinh':'Sắp Đội Hình','chon-chung':'Vòng Chọn Chung','ket-thuc':'Tính Điểm Danh Vọng'}[s.pha]||s.pha;}
function roman(n){return ['','I','II','III','IV'][n]||n;}

function specialPanel(s){if(s.pha==='ky-ngo')return encounterPanel(s);if(s.pha==='loi')return augmentPanel(s);if(s.pha==='chon-chung')return carouselPanel(s);if(s.pha==='ket-thuc')return endPanel(s);return '';}
function encounterPanel(s){const k=s.kyNgoHienTai;return `<section class="special-banner"><div><span class="eyebrow">VÒNG KỲ NGỘ • ${esc(k.loai.toUpperCase())}</span><h2>${esc(k.ten)}</h2><p>${esc(k.moTa)}</p></div><div class="choice-progress">${s.nguoiChoi.map(p=>`<span class="${k.choices[p.id]?'done':''}">${esc(p.ten)}</span>`).join('')}</div></section>`;}
function augmentPanel(s){return `<section class="special-banner augment"><div><span class="eyebrow">LÕI NÂNG CẤP</span><h2>Chọn một Lõi ${s.loiDangDung.tier==='bac'?'Bạc':s.loiDangDung.tier==='vang'?'Vàng':'Đa Sắc'}</h2><p>Mỗi người chọn kín một Lõi. Có thể Đổi Lõi đúng một lần trong cả ván.</p></div><div class="choice-progress">${s.nguoiChoi.map(p=>`<span class="${s.loiDangDung.choices[p.id]?'done':''}">${esc(p.ten)}</span>`).join('')}</div></section>`;}
function carouselPanel(s){const c=s.carousel,current=game.player(c.order[c.turn]);return `<section class="special-banner"><div><span class="eyebrow">VÒNG CHỌN CHUNG</span><h2>Đến lượt ${esc(current?.ten)}</h2><p>Thứ tự ưu tiên: Máu thấp → Điểm Danh Vọng thấp → Quyền Ưu Tiên thấp.</p></div><div class="carousel-options">${c.choices.map((x,i)=>{const ch=champ(x.tuongId);return `<button class="carousel-card ${x.takenBy?'taken':''}" data-carousel="${i}" ${x.takenBy?'disabled':''}><b>${esc(ch?.ten||'Trống')}</b><span>${esc(component(x.componentId)?.ten||'')}</span></button>`}).join('')}</div></section>`;}
function endPanel(s){const ranking=[...s.nguoiChoi].sort((a,b)=>b.diemDanhVong-a.diemDanhVong||b.mau-a.mau||b.cap-a.cap||b.soTranThang-a.soTranThang||b.vang-a.vang);return `<section class="end-screen"><div class="trophy">★</div><h2>${esc(ranking[0].ten)} dẫn đầu Điểm Danh Vọng</h2><div class="ranking">${ranking.map((p,i)=>`<div><strong>${i+1}</strong><span>${esc(p.ten)}</span><b>${p.diemDanhVong} điểm</b><small>♥ ${p.mau} · Cấp ${p.cap} · ${p.soTranThang} thắng · ${p.vang} Vàng</small></div>`).join('')}</div><button data-cmd="new" class="primary">Ván mới</button></section>`;}

function marketPanel(s){return `<section class="market-zone"><div class="section-head"><div><span class="eyebrow">CHỢ CHUNG</span><h2>${s.choChung.length} ô · ${Math.ceil(s.choChung.length/4)} dãy</h2></div><div class="priority">Quyền Ưu Tiên: <b>${esc(s.nguoiChoi[s.nguoiUuTien].ten)}</b>${s.biTranhMua.length?`<small>Bị Tranh Mua: ${s.biTranhMua.map(id=>champ(id)?.ten).join(', ')}</small>`:''}</div></div><div class="market-grid">${s.choChung.map((slot,i)=>cardView(slot.tuongId,{market:true,index:i,bac:slot.bac,selected:selectedMarket.has(i)})).join('')}</div></section>`;}
function cardView(id,opt={}){if(!id)return `<div class="champ-card empty"><span>Bậc ${opt.bac||'?'}</span><b>Kho đã hết</b></div>`;const c=champ(id),star=opt.card?.sao||1;return `<button class="champ-card tier-${c.bac} ${opt.selected?'selected':''}" ${opt.market?`data-market="${opt.index}"`:''} ${opt.zone?`data-card="${opt.zone}:${opt.index}"`:''}><span class="cost">${c.gia}</span><span class="portrait">${c.ten.slice(0,1)}</span><span class="stars">${'★'.repeat(star)}</span><strong>${esc(c.ten)}</strong><small>${esc(c.toc)} · ${esc(c.he)}</small><div class="stats"><span>◆ ${c.chiSo[star].tuyenTruoc}</span><span>✦ ${c.chiSo[star].hoaLuc}</span><span>⌁ ${c.chiSo[star].hopLuc}</span></div>${opt.card?.trangBi?.length?`<div class="mini-items">${opt.card.trangBi.map(id=>`<i title="${esc(item(id)?.ten)}">●</i>`).join('')}</div>`:''}</button>`;}

function playerBoard(p){const stats=game.teamStats(p.id);return `<section class="player-board"><div class="player-banner"><div><span class="eyebrow">BẢNG NGƯỜI CHƠI</span><h2>${esc(p.ten)}</h2></div><div class="resource-strip"><span>♥ <b>${p.mau}</b> Máu</span><span>◈ <b>${p.vang}</b> Vàng</span><span>▲ <b>Cấp ${p.cap}</b></span><span>◇ <b>${p.kinhNghiem}</b> Kinh nghiệm</span><span>↯ <b>${p.chuoi.soLan}</b> ${p.chuoi.loai==='khong'?'Chuỗi':p.chuoi.loai}</span></div></div>
    <div class="combat-summary"><span>◆ Tuyến Trước <b>${stats.tuyenTruoc}</b></span><span>✦ Hỏa Lực <b>${stats.hoaLuc}</b></span><span>⌁ Hợp Lực <b>${stats.hopLuc}</b></span></div>
    <div class="board-label">Sân · tối đa ${p.cap} tướng</div><div class="arena">${p.san.map((x,i)=>x?cardView(x.tuongId,{card:x,zone:'san',index:i}):`<button class="board-slot" data-empty="san:${i}">${i+1}</button>`).join('')}</div>
    <div class="board-label">Băng Ghế · 8 ô</div><div class="bench">${p.bangGhe.map((x,i)=>x?cardView(x.tuongId,{card:x,zone:'bangGhe',index:i}):`<button class="bench-slot" data-empty="bangGhe:${i}">${i+1}</button>`).join('')}</div>
    <div class="lower-board"><div class="hold"><h3>Hàng Giữ</h3><div>${[0,1].map(i=>{const h=p.hangGiu[i];return h?`<button class="hold-card" data-hold="${i}"><b>${esc(champ(h.tuongId).ten)}</b><small>hết hạn sau Vòng ${h.expiresAfterRound}</small></button>`:'<span class="hold-empty">Trống</span>'}).join('')}</div></div>${inventory(p)}${objectives(p)}</div></section>`;}
function inventory(p){return `<div class="inventory"><h3>Trang Bị</h3><div class="components">${p.thanhPhan.length?p.thanhPhan.map((id,i)=>`<button data-component="${i}" title="Thành Phần">${esc(component(id)?.ten||id)}</button>`).join(''):'<small>Chưa có Thành Phần.</small>'}</div><div class="items">${p.trangBiRoi.length?p.trangBiRoi.map((id,i)=>`<button data-item="${i}">${esc(item(id)?.ten||id)}</button>`).join(''):'<small>Chưa có Trang Bị rời.</small>'}</div></div>`;}
function objectives(p){return `<div class="objectives"><h3>Mục Tiêu Cá Nhân</h3>${p.mucTieuCaNhan.map(id=>{const o=objective(id),done=p.mucTieuHoanThanh.includes(id);return `<div class="objective ${done?'done':''}"><b>${esc(o?.ten)}</b><small>${esc(o?.moTa)}</small><span>${done?'Hoàn thành':`${o?.points||0} điểm`}</span></div>`}).join('')}</div>`;}
function traitsPanel(p){const t=game.activeTraits(p.id);return `<section class="side-card"><h3>Tộc/Hệ đang hoạt động</h3>${Object.keys(t).length?Object.entries(t).map(([name,x])=>`<div class="trait"><b>${esc(name)}</b><span>${x.count} / mốc ${x.moc}</span></div>`).join(''):'<small>Đưa tướng lên sân để kích hoạt.</small>'}</section>`;}
function roundTrack(s){const specials={1:'Kỳ Ngộ',2:'Lõi Bạc',3:'Thử Thách',4:'Kỳ Ngộ',6:'Lõi Vàng + Thử Thách',7:'Kỳ Ngộ',9:'Thử Thách',10:'Kỳ Ngộ + Lõi Đa Sắc',12:'Thử Thách'};return `<section class="side-card round-track"><h3>Hành trình 12 Vòng</h3><div>${Array.from({length:12},(_,i)=>i+1).map(r=>`<span class="${r===s.vong?'current':r<s.vong?'past':''}" title="${specials[r]||'Giao Tranh'}">${r}</span>`).join('')}</div><small>${specials[s.vong]||'Giao Tranh giữa người chơi'}</small></section>`;}
function logPanel(s){return `<section class="side-card log"><h3>Nhật ký ván</h3><div>${s.nhatKy.slice(0,12).map(x=>`<p><b>V${x.vong}${x.nhip?`·N${x.nhip}`:''}</b> ${esc(x.msg)}</p>`).join('')}</div></section>`;}

function actionDock(s,p){if(s.pha==='ky-ngo')return encounterDock(s,p);if(s.pha==='loi')return augmentDock(s,p);if(s.pha==='sap-doi-hinh')return `<footer class="action-dock"><div><b>Sắp Đội Hình</b><small>Hoàn tất vị trí và Trang Bị trước khi tiếp tục.</small></div><button class="primary" data-cmd="confirm-lineup">Khóa đội hình & giải quyết</button></footer>`;if(s.pha==='ket-thuc'||s.pha==='chon-chung')return '<footer class="action-dock compact"><small>Thực hiện lựa chọn ở khu vực trung tâm.</small></footer>';if(s.pha!=='chuan-bi')return '';
  const locked=!!s.pendingActions[p.id];return `<footer class="action-dock"><div class="beat-info"><b>Nhịp Chuẩn Bị ${s.nhipChuanBi}/4</b><small>${locked?'Đã khóa lựa chọn — chờ những người khác.':'Chọn kín một Hành Động.'}</small></div><div class="actions">${['mua','lam-moi','luyen-cap','giu','tich-luy'].map(a=>`<button data-action="${a}" ${locked?'disabled':''}>${{'mua':'Mua Tướng','lam-moi':'Làm Mới Chợ','luyen-cap':'Luyện Cấp','giu':'Giữ Tướng','tich-luy':'Tích Lũy'}[a]}</button>`).join('')}</div></footer>`;}
function encounterDock(s,p){const k=s.kyNgoHienTai;if(k.choices[p.id])return `<footer class="action-dock"><div><b>${esc(p.ten)}</b><small>Đã khóa lựa chọn Kỳ Ngộ.</small></div><button data-cmd="next-unpicked">Chuyển người chơi</button></footer>`;return `<footer class="action-dock"><div><b>${esc(p.ten)} chọn kín</b><small>Không hiển thị lựa chọn đã khóa của người khác.</small></div><div class="actions">${k.luaChon.map(c=>`<button data-encounter="${c.id}" ${p.vang<c.cost?'disabled':''}><b>${esc(c.ten)}</b><small>${c.cost} Vàng</small></button>`).join('')}</div></footer>`;}
function augmentDock(s,p){const L=s.loiDangDung;if(L.choices[p.id])return `<footer class="action-dock"><div><b>${esc(p.ten)}</b><small>Đã khóa Lõi.</small></div><button data-cmd="next-unpicked">Chuyển người chơi</button></footer>`;return `<footer class="action-dock augment-dock"><button data-cmd="reroll" ${p.doiLoiDaDung?'disabled':''}>Đổi Lõi ${p.doiLoiDaDung?'(đã dùng)':''}</button>${L.offers[p.id].map(id=>{const a=aug(id);return `<button class="augment-choice" data-augment="${id}"><b>${esc(a.ten)}</b><small>${esc(a.moTa)}</small></button>`}).join('')}</footer>`;}

function wire(){document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>{activePlayerId=b.dataset.player;selectedMarket.clear();selectedCard=null;render();});document.querySelectorAll('[data-market]').forEach(b=>b.onclick=()=>{const i=+b.dataset.market;if(selectedMarket.has(i))selectedMarket.delete(i);else if(selectedMarket.size<2)selectedMarket.add(i);render();});
  document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>handleAction(b.dataset.action));
  document.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>handleCard(b.dataset.card));document.querySelectorAll('[data-hold]').forEach(b=>b.onclick=()=>{selectedMarket.clear();showHoldMenu(+b.dataset.hold);});
  document.querySelectorAll('[data-encounter]').forEach(b=>b.onclick=()=>act(()=>{game.chooseEncounter(activePlayerId,b.dataset.encounter);selectNextUnpicked();}));document.querySelectorAll('[data-augment]').forEach(b=>b.onclick=()=>act(()=>{game.chooseAugment(activePlayerId,b.dataset.augment);selectNextUnpicked();},'level'));
  document.querySelectorAll('[data-carousel]').forEach(b=>b.onclick=()=>act(()=>game.chooseCarousel(game.state.carousel.order[game.state.carousel.turn],+b.dataset.carousel),'level'));
  document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>command(b.dataset.cmd));
  let chosenComponents=[];document.querySelectorAll('[data-component]').forEach(b=>b.onclick=()=>{chosenComponents.push(+b.dataset.component);if(chosenComponents.length===2){act(()=>game.combineItem(activePlayerId,chosenComponents[0],chosenComponents[1]),'star');chosenComponents=[];}else toast('Chọn thêm một Thành Phần để ghép.');});
  document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{const idx=+b.dataset.item;if(!selectedCard)return toast('Chọn một tướng trên sân hoặc Băng Ghế trước.','loi');const [zone,i]=selectedCard.split(':');act(()=>game.equip(activePlayerId,zone,+i,idx));});
  if(game.state.pendingRefreshBuy)showRefreshBuy();
}
function selectNextUnpicked(){const s=game.state;if(s.pha==='ky-ngo'){const p=s.nguoiChoi.find(x=>!s.kyNgoHienTai.choices[x.id]);if(p)activePlayerId=p.id;}else if(s.pha==='loi'){const p=s.nguoiChoi.find(x=>!s.loiDangDung.choices[x.id]);if(p)activePlayerId=p.id;}else if(s.pha==='chuan-bi'){const p=s.nguoiChoi.find(x=>!s.pendingActions[x.id]);if(p)activePlayerId=p.id;}}
function handleAction(type){const p=game.player(activePlayerId);if(type==='mua'){const targets=[...selectedMarket].map(i=>({source:'market',index:i}));if(!targets.length)return toast('Chọn tối đa 2 tướng trong Chợ trước.','loi');act(()=>{game.submitAction(p.id,{type,targets});selectedMarket.clear();selectNextUnpicked();});}
  if(type==='giu'){if(selectedMarket.size!==1)return toast('Chọn đúng 1 tướng trong Chợ trước.','loi');const index=[...selectedMarket][0];act(()=>{game.submitAction(p.id,{type,index});selectedMarket.clear();selectNextUnpicked();});}
  if(type==='lam-moi'){const rows=Math.ceil(game.state.choChung.length/4),row=prompt(`Chọn dãy Chợ cần Làm Mới (1–${rows})`,'1');if(row===null)return;const r=+row-1;if(r<0||r>=rows)return toast('Dãy không hợp lệ.','loi');act(()=>{game.submitAction(p.id,{type,row:r});selectNextUnpicked();});}
  if(type==='luyen-cap'){const times=+prompt('Mua bao nhiêu lần 4 Kinh nghiệm? (1–3)','1');if(![1,2,3].includes(times))return;act(()=>{game.submitAction(p.id,{type,times});selectNextUnpicked();},'level');}
  if(type==='tich-luy')act(()=>{game.submitAction(p.id,{type});selectNextUnpicked();});}
function handleCard(spec){if(game.state.pha!=='chuan-bi'&&game.state.pha!=='sap-doi-hinh')return;selectedCard=spec;const [zone,index]=spec.split(':'),p=game.player(activePlayerId),card=p[zone][+index],c=champ(card.tuongId);openModal(`<h2>${esc(c.ten)} ${'★'.repeat(card.sao)}</h2><p>${esc(c.toc)} · ${esc(c.he)}</p><div class="modal-actions"><button data-modal="move">Chuyển sang ${zone==='san'?'Băng Ghế':'sân'}</button><button data-modal="merge2">Ghép 2★</button><button data-modal="merge3">Ghép 3★</button><button data-modal="sell">Bán tướng</button></div><p><small>Chọn Trang Bị rời ở bảng người chơi sau khi đóng cửa sổ để gắn lên tướng này.</small></p>`);document.querySelector('[data-modal="move"]').onclick=()=>{closeModal();act(()=>game.moveCard(activePlayerId,zone,+index,zone==='san'?'bangGhe':'san'));};document.querySelector('[data-modal="merge2"]').onclick=()=>{closeModal();act(()=>game.merge(activePlayerId,c.id,2),'star');};document.querySelector('[data-modal="merge3"]').onclick=()=>{closeModal();act(()=>game.merge(activePlayerId,c.id,3),'star');};document.querySelector('[data-modal="sell"]').onclick=()=>{closeModal();act(()=>game.sell(activePlayerId,zone,+index));};}
function showHoldMenu(i){const p=game.player(activePlayerId),h=p.hangGiu[i];if(!h)return;openModal(`<h2>${esc(champ(h.tuongId).ten)}</h2><p>Đã đặt cọc 1 Vàng. Mua trước khi hết Vòng ${h.expiresAfterRound}.</p><button data-modal="buyhold" class="primary">Mua từ Hàng Giữ</button>`);document.querySelector('[data-modal="buyhold"]').onclick=()=>{closeModal();act(()=>game.buy(activePlayerId,'hold',i));};}
function showRefreshBuy(){const pr=game.state.pendingRefreshBuy,p=game.player(pr.playerId);const start=pr.row*4;openModal(`<h2>${esc(p.ten)} — quyền mua sau Làm Mới</h2><p>Bạn có thể mua ngay tối đa 1 tướng trong dãy vừa mở, hoặc bỏ qua.</p><div class="refresh-picks">${game.state.choChung.slice(start,start+4).map((s,i)=>`<button data-rbuy="${i}" ${!s.tuongId?'disabled':''}>${esc(champ(s.tuongId)?.ten||'Trống')}</button>`).join('')}</div><button data-rbuy="skip">Bỏ qua</button>`,false);document.querySelectorAll('[data-rbuy]').forEach(b=>b.onclick=()=>{const v=b.dataset.rbuy;closeModal();act(()=>game.resolveRefreshBuy(v==='skip'?null:+v));});}
function command(cmd){if(cmd==='save'){save();toast('Đã lưu ván trên thiết bị.');}if(cmd==='rules')showRules();if(cmd==='settings'){audioEnabled=!audioEnabled;render();}if(cmd==='home'){if(confirm('Rời bàn chơi? Ván hiện tại đã được lưu.')){save();game=null;newGameScreen();}}if(cmd==='new'){localStorage.removeItem(SAVE_KEY);game=null;newGameScreen();}if(cmd==='confirm-lineup')act(()=>game.confirmLineup(),'hurt');if(cmd==='next-unpicked'){selectNextUnpicked();render();}if(cmd==='reroll')act(()=>game.rerollAugments(activePlayerId));}
function showRules(){openModal(`<h2>Luật nhanh</h2><div class="rules"><h3>Cấu trúc ván</h3><p>4 Giai Đoạn × 3 Vòng = 12 Vòng Đấu. Mỗi vòng: Thu Nhập → +2 Kinh nghiệm → Chợ Chung → 4 Nhịp Chuẩn Bị → Sắp Đội Hình → Giao Tranh/Thử Thách → Dọn Vòng.</p><h3>Năm Hành Động</h3><p><b>Mua Tướng:</b> tối đa 2. <b>Làm Mới Chợ:</b> 2 Vàng, đổi một dãy 4 ô rồi được quyền mua 1. <b>Luyện Cấp:</b> 4 Vàng = 4 Kinh nghiệm, tối đa 3 lần. <b>Giữ Tướng:</b> đặt cọc 1 Vàng. <b>Tích Lũy:</b> +2 Vàng, tối đa 1 lần/vòng.</p><h3>Giao Tranh</h3><p>So riêng Tuyến Trước, Hỏa Lực, Hợp Lực. Thắng ít nhất 2/3 chỉ số để thắng trận. Nếu 1 thắng–1 thua–1 hòa, so tổng Sao.</p><h3>Lãi</h3><p>10/20/30+ Vàng cho +1/+2/+3 Vàng Lãi. Chuỗi 2/4/6+ cho +1/+2/+3.</p><h3>Ghép Sao</h3><p>3 bản cùng tên → 2★. 6 bản cùng tên → 3★. Bán tướng hoàn trả đúng số bản sao vào Hàng Hoàn Trả.</p><h3>Điểm Danh Vọng</h3><p>Cuối Vòng 12 tính từ Giao Tranh, Máu, Cấp, Vàng, Tộc/Hệ, tướng 3★, Mục Tiêu và hiệu ứng khác.</p></div>`);}
function openModal(html,closable=true){closeModal();const d=document.createElement('div');d.className='modal-wrap';d.innerHTML=`<div class="modal">${closable?'<button class="modal-close">×</button>':''}${html}</div>`;document.body.append(d);d.querySelector('.modal-close')?.addEventListener('click',closeModal);}
function closeModal(){document.querySelector('.modal-wrap')?.remove();}

if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
if(!load())newGameScreen();else render();
