import {CHAMPIONS,TRAITS,COMPONENTS,ITEMS,AUGMENTS,ENCOUNTERS,OBJECTIVES,NEUTRAL} from './data.js';

export const XP_NEED=[0,2,4,6,8,12,18,24,32,44];
export const MARKET_STRUCTURE={
  '2-3':{1:[5,3,0,0,0],2:[3,3,2,0,0],3:[1,2,3,2,0],4:[1,1,2,2,2]},
  '4-5':{1:[7,5,0,0,0],2:[4,4,4,0,0],3:[2,3,4,3,0],4:[1,2,3,3,3]},
  '6-8':{1:[9,7,0,0,0],2:[5,6,5,0,0],3:[3,4,5,4,0],4:[2,3,4,4,3]}
};
const COPIES={'2-3':[6,6,5,4,3],'4-5':[8,7,6,5,4],'6-8':[10,9,8,6,5]};
const COMBAT_ROUNDS=new Set([1,2,4,5,7,8,10,11]);
const NEUTRAL_ROUNDS=new Set([3,6,9,12]);
const CAROUSEL_ROUNDS=new Set([3,6,9]);
const ENCOUNTER_ROUNDS=new Set([1,4,7,10]);
const AUGMENT_ROUNDS={2:'bac',6:'vang',10:'da-sac'};

function xmur3(str){let h=1779033703^str.length;for(let i=0;i<str.length;i++){h=Math.imul(h^str.charCodeAt(i),3432918353);h=h<<13|h>>>19;}return()=>{h=Math.imul(h^h>>>16,2246822507);h=Math.imul(h^h>>>13,3266489909);return(h^h>>>16)>>>0;};}
function mulberry32(a){return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
export class RNG{constructor(seed='BGTF'){this.seed=seed;this.step=0;this.r=mulberry32(xmur3(seed)());}next(){this.step++;return this.r();}int(n){return Math.floor(this.next()*n);}pick(a){return a.length?a[this.int(a.length)]:null;}shuffle(a){for(let i=a.length-1;i>0;i--){const j=this.int(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}}

const group=n=>n<=3?'2-3':n<=5?'4-5':'6-8';
const stageOf=r=>Math.ceil(r/3);
const emptySlots=n=>Array.from({length:n},()=>null);
const clone=o=>structuredClone(o);

export class GameEngine{
  constructor(names=['Người chơi 1','Người chơi 2'],seed=`BGTF-${Date.now()}`){
    if(names.length<2||names.length>8) throw new Error('Số người chơi phải từ 2 đến 8.');
    this.rng=new RNG(seed); this.dataVersion='4.0-web-0.1';
    this.state={phienBanDuLieu:this.dataVersion,hatNgauNhien:seed,rngStep:0,soNguoiChoi:names.length,giaiDoan:1,vong:1,nhipChuanBi:0,pha:'khoi-tao',nguoiUuTien:0,nguoiChoi:[],choChung:[],khoTuong:{1:[],2:[],3:[],4:[],5:[]},hangHoanTra:{1:[],2:[],3:[],4:[],5:[]},biTranhMua:[],pendingActions:{},pendingRefreshBuy:null,kyNgoHienTai:null,loiDangDung:null,mucTieuCongKhai:[],lichSuGiaoTranh:[],nhatKy:[],carousel:null};
    this.#makePools();
    this.state.nguoiChoi=names.map((ten,i)=>this.#makePlayer(i,ten));
    this.#dealObjectives(); this.#startingChampions();
    this.#prepareSpecialOrRound(); this.#syncRng();
  }
  #log(msg,type='thong-tin'){this.state.nhatKy.unshift({vong:this.state.vong,nhip:this.state.nhipChuanBi,msg,type,at:Date.now()});this.state.nhatKy=this.state.nhatKy.slice(0,120);}
  #syncRng(){this.state.rngStep=this.rng.step;}
  #makePools(){const cfg=COPIES[group(this.state.soNguoiChoi)];for(const c of CHAMPIONS){for(let i=0;i<cfg[c.bac-1];i++)this.state.khoTuong[c.bac].push(c.id);}for(let t=1;t<=5;t++)this.rng.shuffle(this.state.khoTuong[t]);}
  #makePlayer(i,ten){return{id:`p${i+1}`,ten,mauNhanDien:i,mau:40,vang:5,kinhNghiem:0,cap:1,diemDanhVong:0,chuoi:{loai:'khong',soLan:0},san:emptySlots(10),bangGhe:emptySlots(8),hangGiu:[],thanhPhan:[],trangBiRoi:[],loiNangCap:[],mucTieuCaNhan:[],mucTieuHoanThanh:[],hanhDongDaDungTrongVong:[],soTranThang:0,lichSuDoiThu:[],doiLoiDaDung:false};}
  #dealObjectives(){const deck=this.rng.shuffle([...OBJECTIVES]);this.state.nguoiChoi.forEach((p,i)=>{p.mucTieuCaNhan=deck.slice(i*2,i*2+2).map(x=>x.id);});this.state.mucTieuCongKhai=deck.slice(this.state.nguoiChoi.length*2,this.state.nguoiChoi.length*2+3).map(x=>({id:x?.id,claimed:[]})).filter(x=>x.id);}
  #drawTier(t){if(!this.state.khoTuong[t].length&&this.state.hangHoanTra[t].length){this.state.khoTuong[t]=this.rng.shuffle(this.state.hangHoanTra[t].splice(0));}return this.state.khoTuong[t].pop()??null;}
  #returnCard(id){const c=this.champion(id);if(c)this.state.hangHoanTra[c.bac].push(id);}
  #startingChampions(){for(const p of this.state.nguoiChoi){const id=this.#drawTier(1);if(id)p.bangGhe[0]={tuongId:id,soBanSao:1,sao:1,trangBi:[]};}}
  champion(id){return CHAMPIONS.find(c=>c.id===id);}
  player(id){return this.state.nguoiChoi.find(p=>p.id===id);}
  #prepareSpecialOrRound(){this.state.giaiDoan=stageOf(this.state.vong);if(ENCOUNTER_ROUNDS.has(this.state.vong)){this.#startEncounter();return;}if(AUGMENT_ROUNDS[this.state.vong]){this.#startAugment(AUGMENT_ROUNDS[this.state.vong]);return;}this.startRound();}
  #startEncounter(){const enc=clone(this.rng.pick(ENCOUNTERS));this.state.kyNgoHienTai={...enc,choices:{},resolved:false};this.state.pha='ky-ngo';this.#log(`Vòng Kỳ Ngộ: ${enc.ten}.`,'ky-ngo');}
  chooseEncounter(playerId,choiceId){const k=this.state.kyNgoHienTai;if(this.state.pha!=='ky-ngo'||!k)throw new Error('Không có Vòng Kỳ Ngộ đang chờ.');const p=this.player(playerId),ch=k.luaChon.find(x=>x.id===choiceId);if(!p||!ch)throw new Error('Lựa chọn không hợp lệ.');if(p.vang<ch.cost)throw new Error('Không đủ Vàng.');k.choices[playerId]=choiceId;if(Object.keys(k.choices).length===this.state.soNguoiChoi)this.#resolveEncounter();}
  #resolveEncounter(){const k=this.state.kyNgoHienTai;let total=0;for(const p of this.state.nguoiChoi){const ch=k.luaChon.find(x=>x.id===k.choices[p.id]);p.vang-=ch.cost;total+=ch.cost;this.#applyReward(p,ch.reward);if(ch.risk&&this.rng.next()<0.5)p.mau=Math.max(0,p.mau-(ch.risk.health||0));}
    if(k.loai==='chung-suc'){const reward=total>=this.state.soNguoiChoi*3?2:total>=this.state.soNguoiChoi?1:0;for(const p of this.state.nguoiChoi)for(let i=0;i<reward;i++)this.#giveComponent(p);}
    k.resolved=true;this.#log(`Kỳ Ngộ ${k.ten} đã được giải quyết.`,'ky-ngo');if(AUGMENT_ROUNDS[this.state.vong])this.#startAugment(AUGMENT_ROUNDS[this.state.vong]);else this.startRound();}
  #startAugment(tier){this.state.loiDangDung={tier,choices:{},offers:{}};for(const p of this.state.nguoiChoi)this.state.loiDangDung.offers[p.id]=this.rng.shuffle([...AUGMENTS[tier]]).slice(0,3).map(x=>x.id);this.state.pha='loi';this.#log(`Chọn Lõi Nâng Cấp bậc ${tier==='bac'?'Bạc':tier==='vang'?'Vàng':'Đa Sắc'}.`,'loi');}
  chooseAugment(playerId,augmentId){if(this.state.pha!=='loi')throw new Error('Không ở pha chọn Lõi.');const p=this.player(playerId),tier=this.state.loiDangDung.tier,offer=this.state.loiDangDung.offers[playerId]||[];if(!p||!offer.includes(augmentId))throw new Error('Lõi không nằm trong lựa chọn.');p.loiNangCap.push(augmentId);const aug=AUGMENTS[tier].find(x=>x.id===augmentId);this.#applyReward(p,aug.effect);this.state.loiDangDung.choices[playerId]=augmentId;if(Object.keys(this.state.loiDangDung.choices).length===this.state.soNguoiChoi)this.startRound();}
  rerollAugments(playerId){const p=this.player(playerId),tier=this.state.loiDangDung?.tier;if(this.state.pha!=='loi'||!p||p.doiLoiDaDung)throw new Error('Không thể Đổi Lõi.');p.doiLoiDaDung=true;this.state.loiDangDung.offers[playerId]=this.rng.shuffle([...AUGMENTS[tier]]).slice(0,3).map(x=>x.id);}
  #applyReward(p,r={}){p.vang+=r.gold||0;for(let i=0;i<(r.xp||0);i++)this.#gainXp(p,1);for(let i=0;i<(r.components||0);i++)this.#giveComponent(p);}
  #giveComponent(p){p.thanhPhan.push(this.rng.pick(COMPONENTS).id);}
  startRound(){this.state.pha='thu-nhap';this.state.nhipChuanBi=0;this.state.pendingActions={};this.state.nguoiChoi.forEach(p=>{p.hanhDongDaDungTrongVong=[];const cap=p.loiNangCap.includes('lai-kep')?4:3;const interest=Math.min(cap,Math.floor(p.vang/10));const streak=p.chuoi.soLan>=6?3:p.chuoi.soLan>=4?2:p.chuoi.soLan>=2?1:0;p.vang+=5+interest+streak;this.#gainXp(p,2);});this.#openMarket();this.state.nhipChuanBi=1;this.state.pha='chuan-bi';this.#log(`Vòng ${this.state.vong} bắt đầu. Thu Nhập và 2 Kinh nghiệm đã được nhận.`,'vong');}
  #openMarket(){for(const s of this.state.choChung)if(s.tuongId)this.#returnCard(s.tuongId);for(let t=1;t<=5;t++){if(this.state.hangHoanTra[t].length)this.state.khoTuong[t].push(...this.rng.shuffle(this.state.hangHoanTra[t].splice(0)));this.rng.shuffle(this.state.khoTuong[t]);}
    this.state.choChung=[];const structure=MARKET_STRUCTURE[group(this.state.soNguoiChoi)][this.state.giaiDoan];structure.forEach((n,i)=>{for(let k=0;k<n;k++)this.state.choChung.push({bac:i+1,tuongId:this.#drawTier(i+1)});});
    this.state.biTranhMua=[];if(this.state.soNguoiChoi===2&&this.state.vong>=4){const tiers=[...new Set(this.state.choChung.map(s=>s.bac))];for(let i=0;i<2;i++){const t=this.rng.pick(tiers),id=this.#drawTier(t);if(id)this.state.biTranhMua.push(id);}}
  }
  submitAction(playerId,action){if(this.state.pha!=='chuan-bi')throw new Error('Không ở Nhịp Chuẩn Bị.');if(this.state.pendingActions[playerId])throw new Error('Người chơi đã khóa lựa chọn.');if(!['mua','lam-moi','luyen-cap','giu','tich-luy'].includes(action.type))throw new Error('Hành động không hợp lệ.');this.state.pendingActions[playerId]=clone(action);if(Object.keys(this.state.pendingActions).length===this.state.soNguoiChoi)this.resolveBeat();}
  resolveBeat(){const order=this.priorityOrder();const nonMarket=['luyen-cap','tich-luy'];for(const pid of order){const a=this.state.pendingActions[pid];if(nonMarket.includes(a.type))this.#resolveAction(pid,a);}for(const pid of order){const a=this.state.pendingActions[pid];if(!nonMarket.includes(a.type))this.#resolveAction(pid,a);}this.state.pendingActions={};if(this.state.pendingRefreshBuy)return;this.#finishBeat();}
  priorityOrder(){const a=[];for(let i=0;i<this.state.soNguoiChoi;i++)a.push(this.state.nguoiChoi[(this.state.nguoiUuTien+i)%this.state.soNguoiChoi].id);return a;}
  #resolveAction(pid,a){const p=this.player(pid);try{if(a.type==='tich-luy'){if(p.hanhDongDaDungTrongVong.includes('tich-luy'))throw new Error('Tích Lũy chỉ dùng một lần mỗi vòng.');p.vang+=2;p.hanhDongDaDungTrongVong.push('tich-luy');this.#log(`${p.ten} dùng Tích Lũy và nhận 2 Vàng.`);}
      if(a.type==='luyen-cap'){const n=Math.max(1,Math.min(3,a.times||1)),cost=n*4;if(p.vang<cost)throw new Error('Không đủ Vàng để Luyện Cấp.');p.vang-=cost;this.#gainXp(p,n*4);this.#log(`${p.ten} Luyện Cấp ${n} lần.`);}
      if(a.type==='mua'){for(const target of (a.targets||[]).slice(0,2))this.buy(pid,target.source,target.index);}
      if(a.type==='giu'){this.hold(pid,a.index);}
      if(a.type==='lam-moi'){this.refreshRow(pid,a.row);this.state.pendingRefreshBuy={playerId:pid,row:a.row};}
    }catch(e){this.#log(`${p.ten}: ${e.message}`,'loi');}}
  resolveRefreshBuy(index=null){const pr=this.state.pendingRefreshBuy;if(!pr)return;if(index!==null){const absolute=pr.row*4+index;try{this.buy(pr.playerId,'market',absolute);}catch(e){this.#log(`${this.player(pr.playerId).ten}: ${e.message}`,'loi');}}
    this.state.pendingRefreshBuy=null;this.#finishBeat();}
  #finishBeat(){if(this.state.nhipChuanBi<4){this.state.nhipChuanBi++;this.state.pha='chuan-bi';this.#log(`Bắt đầu Nhịp Chuẩn Bị ${this.state.nhipChuanBi}.`);}else{this.state.pha='sap-doi-hinh';this.#log('Sắp Đội Hình trước khi giải quyết cuối vòng.');}}
  confirmLineup(){if(this.state.pha!=='sap-doi-hinh')throw new Error('Không ở pha Sắp Đội Hình.');for(const p of this.state.nguoiChoi)if(p.san.filter(Boolean).length>p.cap)throw new Error(`${p.ten} có quá nhiều tướng trên sân.`);if(NEUTRAL_ROUNDS.has(this.state.vong))this.#resolveNeutral();else this.#resolveCombat();this.#checkObjectives();this.#cleanupRound();}
  #gainXp(p,amount){if(p.cap>=10)return;p.kinhNghiem+=amount;while(p.cap<10&&p.kinhNghiem>=XP_NEED[p.cap]){p.kinhNghiem-=XP_NEED[p.cap];p.cap++;this.#log(`${p.ten} tăng lên Cấp ${p.cap}.`,'cap');}}
  buy(pid,source,index){const p=this.player(pid);let id=null,discount=0;if(source==='market'){const slot=this.state.choChung[index];if(!slot?.tuongId)throw new Error('Ô Chợ đã trống.');id=slot.tuongId;}else if(source==='hold'){const h=p.hangGiu[index];if(!h)throw new Error('Ô Hàng Giữ trống.');id=h.tuongId;discount=1;}else throw new Error('Nguồn mua không hợp lệ.');const c=this.champion(id),cost=Math.max(0,c.gia-discount);if(p.vang<cost)throw new Error('Không đủ Vàng.');const dest=p.bangGhe.findIndex(x=>!x);const board=p.san.findIndex(x=>!x);if(dest<0&&(board<0||p.san.filter(Boolean).length>=p.cap))throw new Error('Băng Ghế và sân không còn chỗ hợp lệ.');p.vang-=cost;const card={tuongId:id,soBanSao:1,sao:1,trangBi:[]};if(dest>=0)p.bangGhe[dest]=card;else p.san[board]=card;if(source==='market'){const tier=this.state.choChung[index].bac;this.state.choChung[index].tuongId=this.#drawTier(tier);}else p.hangGiu.splice(index,1);this.#log(`${p.ten} mua ${c.ten} với giá ${cost} Vàng.`,'mua');}
  hold(pid,index){const p=this.player(pid),slot=this.state.choChung[index];if(!slot?.tuongId)throw new Error('Ô Chợ trống.');if(p.hangGiu.length>=2)throw new Error('Hàng Giữ đã đầy.');if(p.vang<1)throw new Error('Không đủ Vàng đặt cọc.');p.vang--;p.hangGiu.push({tuongId:slot.tuongId,expiresAfterRound:this.state.vong+1});slot.tuongId=this.#drawTier(slot.bac);this.#log(`${p.ten} Giữ Tướng ${this.champion(p.hangGiu.at(-1).tuongId).ten}.`,'giu');}
  refreshRow(pid,row){const p=this.player(pid),start=row*4;if(p.vang<2)throw new Error('Không đủ 2 Vàng.');if(start<0||start>=this.state.choChung.length)throw new Error('Dãy Chợ không hợp lệ.');p.vang-=2;for(let i=start;i<Math.min(start+4,this.state.choChung.length);i++){const s=this.state.choChung[i];if(s.tuongId)this.#returnCard(s.tuongId);s.tuongId=this.#drawTier(s.bac);}this.#log(`${p.ten} Làm Mới Chợ ở dãy ${row+1}.`,'cho');}
  moveCard(pid,from,index,to){const p=this.player(pid),src=p[from];if(!['san','bangGhe'].includes(from)||!['san','bangGhe'].includes(to)||!src[index])throw new Error('Di chuyển không hợp lệ.');if(to==='san'&&p.san.filter(Boolean).length>=p.cap)throw new Error('Số tướng trên sân đã bằng Cấp.');const dst=p[to],empty=dst.findIndex(x=>!x);if(empty<0)throw new Error(to==='san'?'Sân đã đầy.':'Băng Ghế đã đầy.');dst[empty]=src[index];src[index]=null;}
  merge(pid,champId,targetStar){const p=this.player(pid);const all=[...p.san.map((x,i)=>x&&{zone:'san',i,x}),...p.bangGhe.map((x,i)=>x&&{zone:'bangGhe',i,x})].filter(Boolean).filter(e=>e.x.tuongId===champId);const copies=all.reduce((s,e)=>s+e.x.soBanSao,0),need=targetStar===3?6:3;if(copies<need)throw new Error(`Cần ${need} bản sao.`);let keptItems=[];let remove=need;for(const e of all){if(remove<=0)break;keptItems.push(...e.x.trangBi);remove-=e.x.soBanSao;p[e.zone][e.i]=null;}const slot=p.bangGhe.findIndex(x=>!x);if(slot<0)throw new Error('Cần một ô Băng Ghế trống để ghép.');p.bangGhe[slot]={tuongId:champId,soBanSao:need,sao:targetStar,trangBi:keptItems.slice(0,3)};this.#log(`${p.ten} nâng ${this.champion(champId).ten} lên ${targetStar}★.`,'sao');}
  sell(pid,zone,index){const p=this.player(pid),card=p[zone]?.[index];if(!card)throw new Error('Không có tướng để bán.');const c=this.champion(card.tuongId),refund=c.gia*card.soBanSao-(card.sao===2?1:card.sao===3?2:0);p.vang+=refund;p.trangBiRoi.push(...card.trangBi);for(let i=0;i<card.soBanSao;i++)this.#returnCard(card.tuongId);p[zone][index]=null;this.#log(`${p.ten} bán ${c.ten}, nhận ${refund} Vàng.`,'ban');}
  combineItem(pid,aIndex,bIndex){const p=this.player(pid);if(aIndex===bIndex||!p.thanhPhan[aIndex]||!p.thanhPhan[bIndex])throw new Error('Chọn hai Thành Phần khác nhau.');const a=p.thanhPhan[aIndex],b=p.thanhPhan[bIndex],it=ITEMS.find(x=>(x.a===a&&x.b===b)||(x.a===b&&x.b===a));if(!it)throw new Error('Cặp Thành Phần này chưa có công thức trong gói dữ liệu.');for(const i of [aIndex,bIndex].sort((x,y)=>y-x))p.thanhPhan.splice(i,1);p.trangBiRoi.push(it.id);return it.id;}
  equip(pid,zone,index,itemIndex){const p=this.player(pid),card=p[zone]?.[index];if(!card)throw new Error('Không có tướng.');if(card.trangBi.length>=3)throw new Error('Tướng đã có 3 Trang Bị.');const item=p.trangBiRoi[itemIndex];if(!item)throw new Error('Trang Bị không tồn tại.');card.trangBi.push(item);p.trangBiRoi.splice(itemIndex,1);}
  activeTraits(pid){const p=this.player(pid),unique=new Map();for(const card of p.san.filter(Boolean))if(!unique.has(card.tuongId))unique.set(card.tuongId,this.champion(card.tuongId));const counts={};for(const c of unique.values()){counts[c.toc]=(counts[c.toc]||0)+1;counts[c.he]=(counts[c.he]||0)+1;}const active={};for(const [name,n] of Object.entries(counts)){const t=TRAITS[name];if(!t)continue;const m=[...t.moc].filter(x=>n>=x).at(-1);if(m)active[name]={count:n,moc:m,bonus:t.bonus[m]};}return active;}
  teamStats(pid){const p=this.player(pid),stats={tuyenTruoc:0,hoaLuc:0,hopLuc:0};for(const card of p.san.filter(Boolean)){const c=this.champion(card.tuongId),base=c.chiSo[card.sao];for(const k of Object.keys(stats))stats[k]+=base[k]||0;for(const iid of card.trangBi){const it=ITEMS.find(x=>x.id===iid);for(const k of Object.keys(stats))stats[k]+=it?.bonus?.[k]||0;}}
    for(const t of Object.values(this.activeTraits(pid)))for(const k of Object.keys(stats))stats[k]+=t.bonus[k]||0;return stats;}
  #pairings(){const ids=this.state.nguoiChoi.map(p=>p.id),shift=(this.state.vong-1)%(ids.length-1||1),rot=[ids[0],...ids.slice(1+shift),...ids.slice(1,1+shift)];const arr=[...rot],pairs=[];if(arr.length%2===1){const solo=arr.pop(),source=arr[(this.state.vong+1)%arr.length];pairs.push([solo,{ghostOf:source}]);}for(let i=0;i<arr.length;i+=2)pairs.push([arr[i],arr[i+1]]);return pairs;}
  #resolveCombat(){this.state.pha='giao-tranh';for(const [a,b] of this.#pairings()){const pa=this.player(a),pb=b?.ghostOf?this.player(b.ghostOf):this.player(b),sa=this.teamStats(pa.id),sb=this.teamStats(pb.id);const wins=['tuyenTruoc','hoaLuc','hopLuc'].map(k=>Math.sign(sa[k]-sb[k]));let result=wins.filter(x=>x>0).length-wins.filter(x=>x<0).length;const starsA=pa.san.filter(Boolean).reduce((s,x)=>s+x.sao,0),starsB=pb.san.filter(Boolean).reduce((s,x)=>s+x.sao,0);if(result===0)result=Math.sign(starsA-starsB);if(result===0){this.#recordCombat(pa,pb,'hoa',0,!!b?.ghostOf);continue;}const winner=result>0?pa:pb,loser=result>0?pb:pa,wstats=result>0?sa:sb,lstats=result>0?sb:sa,wstars=result>0?starsA:starsB,lstars=result>0?starsB:starsA;let dmg=2;if(Object.keys(wstats).every(k=>wstats[k]>lstats[k]))dmg++;if(wstars-lstars>=4)dmg++;dmg=Math.min(4,dmg);if(!(b?.ghostOf&&loser.id===pb.id)){loser.mau=Math.max(0,loser.mau-dmg);this.#updateStreak(loser,'thua');}if(!(b?.ghostOf&&winner.id===pb.id)){winner.soTranThang++;this.#updateStreak(winner,'thang');}this.#recordCombat(winner,loser,'thang',dmg,!!b?.ghostOf);}}
  #updateStreak(p,type){if(p.chuoi.loai===type)p.chuoi.soLan++;else p.chuoi={loai:type,soLan:1};}
  #recordCombat(a,b,result,dmg,ghost){a.lichSuDoiThu.push(b.id);if(!ghost)b.lichSuDoiThu.push(a.id);this.state.lichSuGiaoTranh.push({vong:this.state.vong,a:a.id,b:b.id,result,dmg,ghost});this.#log(`${a.ten} ${result==='hoa'?'hòa':`thắng ${b.ten}${dmg?` và gây ${dmg} Sát Thương`:''}`}.`,'giao-tranh');}
  #resolveNeutral(){this.state.pha='thu-thach';const n=NEUTRAL[this.state.giaiDoan-1];for(const p of this.state.nguoiChoi){const s=this.teamStats(p.id);const hit=['tuyenTruoc','hoaLuc','hopLuc'].filter(k=>s[k]>=n.thresholds[k]).length;if(hit>=1)this.#giveComponent(p);if(hit>=2)this.#giveComponent(p);if(hit>=3){this.#giveComponent(p);p.vang+=2;}this.#log(`${p.ten} đạt ${hit}/3 ngưỡng của ${n.ten}.`,'thu-thach');}}
  #checkObjectives(){for(const p of this.state.nguoiChoi){for(const id of p.mucTieuCaNhan){if(p.mucTieuHoanThanh.includes(id))continue;const o=OBJECTIVES.find(x=>x.id===id);if(o?.test(p,this)){p.mucTieuHoanThanh.push(id);p.diemDanhVong+=o.points;this.#log(`${p.ten} hoàn thành Mục Tiêu ${o.ten}.`,'muc-tieu');}}}}
  #cleanupRound(){for(const p of this.state.nguoiChoi){for(let i=p.hangGiu.length-1;i>=0;i--)if(this.state.vong>=p.hangGiu[i].expiresAfterRound){this.#returnCard(p.hangGiu[i].tuongId);p.hangGiu.splice(i,1);}}
    for(const s of this.state.choChung)if(s.tuongId){this.#returnCard(s.tuongId);s.tuongId=null;}for(const id of this.state.biTranhMua)this.#returnCard(id);this.state.biTranhMua=[];
    if(CAROUSEL_ROUNDS.has(this.state.vong)){this.#startCarousel();return;}this.#advanceRound();}
  #startCarousel(){const count=this.state.soNguoiChoi+2,choices=[];for(let i=0;i<count;i++){const tier=Math.min(5,this.state.giaiDoan+1),id=this.#drawTier(tier)||this.#drawTier(Math.max(1,tier-1));choices.push({tuongId:id,componentId:this.rng.pick(COMPONENTS).id,takenBy:null});}const order=[...this.state.nguoiChoi].sort((a,b)=>a.mau-b.mau||a.diemDanhVong-b.diemDanhVong||this.priorityOrder().indexOf(a.id)-this.priorityOrder().indexOf(b.id)).map(p=>p.id);this.state.carousel={choices,order,turn:0};this.state.pha='chon-chung';this.#log('Bắt đầu Vòng Chọn Chung.','chon-chung');}
  chooseCarousel(playerId,index){const c=this.state.carousel;if(this.state.pha!=='chon-chung'||!c||c.order[c.turn]!==playerId)throw new Error('Chưa tới lượt chọn.');const opt=c.choices[index];if(!opt||opt.takenBy)throw new Error('Lựa chọn đã bị lấy.');const p=this.player(playerId),bench=p.bangGhe.findIndex(x=>!x);if(bench<0)throw new Error('Băng Ghế đầy.');opt.takenBy=playerId;p.bangGhe[bench]={tuongId:opt.tuongId,soBanSao:1,sao:1,trangBi:[]};p.thanhPhan.push(opt.componentId);c.turn++;if(c.turn>=c.order.length)this.#advanceRound();}
  #advanceRound(){this.state.nguoiUuTien=(this.state.nguoiUuTien+1)%this.state.soNguoiChoi;if(this.state.vong>=12){this.finishGame();return;}this.state.vong++;this.state.giaiDoan=stageOf(this.state.vong);this.#prepareSpecialOrRound();}
  finishGame(){this.state.pha='ket-thuc';for(const p of this.state.nguoiChoi){let score=p.diemDanhVong;const w=p.soTranThang;score+=w<=2?0:w<=4?2:w<=6?4:w===7?5:6;score+=p.mau===0?0:p.mau<=10?1:p.mau<=20?3:p.mau<=30?5:6;score+=p.cap<8?0:p.cap===8?2:p.cap===9?4:6;score+=Math.min(4,Math.floor(p.vang/10));score+=Math.min(6,Object.keys(this.activeTraits(p.id)).length);score+=Math.min(6,[...p.san,...p.bangGhe].filter(x=>x?.sao===3).length*2);p.diemDanhVong=score;}this.#log('Ván đấu kết thúc sau Vòng 12.','ket-thuc');}
  serialize(){this.#syncRng();return JSON.stringify(this.state);}
  static fromSave(json){const raw=typeof json==='string'?JSON.parse(json):json;if(raw.phienBanDuLieu!=='4.0-web-0.1')throw new Error('Tệp lưu không tương thích.');const g=Object.create(GameEngine.prototype);g.state=raw;g.rng=new RNG(raw.hatNgauNhien);for(let i=0;i<(raw.rngStep||0);i++)g.rng.next();return g;}
}

export function conservation(engine){const total={};for(const c of CHAMPIONS)total[c.id]=0;for(const tier of [1,2,3,4,5])for(const id of engine.state.khoTuong[tier])total[id]++;for(const tier of [1,2,3,4,5])for(const id of engine.state.hangHoanTra[tier])total[id]++;for(const s of engine.state.choChung)if(s.tuongId)total[s.tuongId]++;for(const id of engine.state.biTranhMua)total[id]++;for(const p of engine.state.nguoiChoi){for(const x of [...p.san,...p.bangGhe].filter(Boolean))total[x.tuongId]+=x.soBanSao;for(const h of p.hangGiu)total[h.tuongId]++;}if(engine.state.carousel)for(const x of engine.state.carousel.choices)if(x.tuongId&&!x.takenBy)total[x.tuongId]++;return total;}
